Tsumiage.create!(
  [
    {
      user_id: '1',
      time: '60',
      genre: 'プログラミング',
      content: 'progateの道場編！',
      created_at: '2020-1-15',
      updated_at: '2020-1-15',
    },
    {
      user_id: '1',
      time: '90',
      genre: 'youtube',
      content: '3本目投稿！',
      created_at: '2020-1-15',
      updated_at: '2020-1-15',
    },
    {
      user_id: '1',
      time: '30',
      genre: '筋トレ・瞑想',
      content: '肩回りを鍛えた！',
      created_at: '2020-1-15',
      updated_at: '2020-1-15',
    },
    {
      user_id: '1',
      time: '60',
      genre: 'プログラミング',
      content: 'progate',
      created_at: '2020-1-13',
      updated_at: '2020-1-13',
    },
    {
      user_id: '1',
      time: '90',
      genre: 'youtube',
      content: '２本目投稿！',
      created_at: '2020-1-13',
      updated_at: '2020-1-13',
    },
    {
      user_id: '1',
      time: '30',
      genre: '筋トレ・瞑想',
      content: '足回りを鍛えた！',
      created_at: '2020-1-14',
      updated_at: '2020-1-14',
    },
    {
      user_id: '1',
      time: '90',
      genre: 'ブログ',
      content: '1記事生産',
      created_at: '2020-1-14',
      updated_at: '2020-1-14',
    },
    {
      user_id: '1',
      time: '60',
      genre: 'プログラミング',
      content: 'ドットインストール',
      created_at: '2020-1-12',
      updated_at: '2020-1-12',
    },
    {
      user_id: '1',
      time: '90',
      genre: 'ブログ',
      content: '1記事生産',
      created_at: '2020-1-12',
      updated_at: '2020-1-12',
    },
    {
      user_id: '1',
      time: '30',
      genre: '資格・読書',
      content: '「ぶち抜く力」を読みました！',
      created_at: '2020-1-12',
      updated_at: '2020-1-12',
    },
    {
      user_id: '1',
      time: '60',
      genre: 'プログラミング',
      content: 'progate',
      created_at: '2020-1-11',
      updated_at: '2020-1-11',
    },
    {
      user_id: '1',
      time: '90',
      genre: 'ブログ',
      content: '健康に関する記事です！',
      created_at: '2020-1-11',
      updated_at: '2020-1-11',
    },
    {
      user_id: '1',
      time: '60',
      genre: 'プログラミング',
      content: 'ドットインストール',
      created_at: '2020-1-10',
      updated_at: '2020-1-10',
    },
    {
      user_id: '1',
      time: '90',
      genre: 'ブログ',
      content: '1記事生産',
      created_at: '2020-1-10',
      updated_at: '2020-1-10',
    },
    {
      user_id: '1',
      time: '30',
      genre: '資格・読書',
      content: 'Life Shift読みました！',
      created_at: '2020-1-10',
      updated_at: '2020-1-10',
    },
    {
      user_id: '1',
      time: '60',
      genre: 'プログラミング',
      content: 'ドットインストール',
      created_at: '2020-1-9',
      updated_at: '2020-1-9',
    },
    {
      user_id: '1',
      time: '90',
      genre: 'youtube',
      content: '初投稿！',
      created_at: '2020-1-9',
      updated_at: '2020-1-9',
    },
    {
      user_id: '1',
      time: '30',
      genre: '筋トレ・瞑想',
      content: '背筋を鍛えた！',
      created_at: '2020-1-9',
      updated_at: '2020-1-9',
    },
    {
      user_id: '1',
      time: '60',
      genre: 'プログラミング',
      content: 'progate',
      created_at: '2020-1-8',
      updated_at: '2020-1-8',
    },
    {
      user_id: '1',
      time: '90',
      genre: 'ブログ',
      content: '1記事生産',
      created_at: '2020-1-8',
      updated_at: '2020-1-8',
    },
    {
      user_id: '1',
      time: '30',
      genre: '資格・読書',
      content: 'ビジネス書',
      created_at: '2020-1-8',
      updated_at: '2020-1-8',
    },
    {
      user_id: '1',
      time: '60',
      genre: 'プログラミング',
      content: 'progate',
      created_at: '2020-1-7',
      updated_at: '2020-1-7',
    },
    {
      user_id: '1',
      time: '90',
      genre: 'ブログ',
      content: '1記事生産',
      created_at: '2020-1-7',
      updated_at: '2020-1-7',
    },
    {
      user_id: '1',
      time: '30',
      genre: '資格・読書',
      content: 'ビジネス書',
      created_at: '2020-1-7',
      updated_at: '2020-1-7',
    },
    {
      user_id: '1',
      time: '60',
      genre: 'プログラミング',
      content: 'progate',
      created_at: '2020-1-6',
      updated_at: '2020-1-6',
    },
    {
      user_id: '1',
      time: '90',
      genre: 'ブログ',
      content: '1記事生産',
      created_at: '2020-1-6',
      updated_at: '2020-1-6',
    },
    {
      user_id: '1',
      time: '30',
      genre: '資格・読書',
      content: 'ビジネス書',
      created_at: '2020-1-6',
      updated_at: '2020-1-6',
    },
    {
      user_id: '1',
      time: '60',
      genre: 'プログラミング',
      content: 'progate',
      created_at: '2020-1-5',
      updated_at: '2020-1-5',
    },
    {
      user_id: '1',
      time: '90',
      genre: 'ブログ',
      content: '1記事生産',
      created_at: '2020-1-5',
      updated_at: '2020-1-5',
    },
    {
      user_id: '1',
      time: '30',
      genre: '資格・読書',
      content: 'ビジネス書',
      created_at: '2020-1-5',
      updated_at: '2020-1-5',
    },

    {
      user_id: '1',
      time: '60',
      genre: 'プログラミング',
      content: 'progate',
      created_at: '2020-1-4',
      updated_at: '2020-1-4',
    },
    {
      user_id: '1',
      time: '90',
      genre: 'ブログ',
      content: '1記事生産',
      created_at: '2020-1-4',
      updated_at: '2020-1-4',
    },
    {
      user_id: '1',
      time: '30',
      genre: '筋トレ・瞑想',
      content: 'ジムで筋トレ',
      created_at: '2020-1-4',
      updated_at: '2020-1-4',
    },

    {
      user_id: '1',
      time: '90',
      genre: 'ブログ',
      content: '1記事生産',
      created_at: '2020-1-3',
      updated_at: '2020-1-3',
    },
    {
      user_id: '1',
      time: '30',
      genre: '筋トレ・瞑想',
      content: 'ジムで筋トレ',
      created_at: '2020-1-3',
      updated_at: '2020-1-3',
    },
    {
      user_id: '1',
      time: '60',
      genre: 'プログラミング',
      content: 'progate',
      created_at: '2020-1-2',
      updated_at: '2020-1-2',
    },
    {
      user_id: '1',
      time: '60',
      genre: '動画編集',
      content: 'youtubeの動画編集',
      created_at: '2020-1-2',
      updated_at: '2020-1-2',
    },
    {
      user_id: '1',
      time: '60',
      genre: 'プログラミング',
      content: 'progate',
      created_at: '2020-1-2',
      updated_at: '2020-1-2',
    },
    {
      user_id: '1',
      time: '60',
      genre: '動画編集',
      content: 'youtubeの動画編集',
      created_at: '2020-1-1',
      updated_at: '2020-1-1',
    },
    {
      user_id: '1',
      time: '60',
      genre: 'プログラミング',
      content: 'progate',
      created_at: '2020-1-1',
      updated_at: '2020-1-1',
    },
    {
      user_id: '1',
      time: '60',
      genre: '動画編集',
      content: 'youtubeの動画編集',
      created_at: '2019-12-31',
      updated_at: '2019-12-31',
    },
    {
      user_id: '1',
      time: '60',
      genre: 'プログラミング',
      content: 'progate',
      created_at: '2019-12-31',
      updated_at: '2019-12-31',
    },
    {
      user_id: '1',
      time: '60',
      genre: '動画編集',
      content: 'youtubeの動画編集',
      created_at: '2019-12-30',
      updated_at: '2019-12-30',
    },
    {
      user_id: '1',
      time: '60',
      genre: 'プログラミング',
      content: 'progate',
      created_at: '2019-12-30',
      updated_at: '2019-12-30',
    },
    {
      user_id: '1',
      time: '60',
      genre: '動画編集',
      content: 'youtubeの動画編集',
      created_at: '2019-12-28',
      updated_at: '2019-12-28',
    },
    






    {
      user_id: '2',
      time: '30',
      genre: '資格・読書',
      content: 'youtube関連の本を読みました！',
      created_at: '2020-1-14',
      updated_at: '2020-1-14',
    },
    {
      user_id: '2',
      time: '60',
      genre: 'プログラミング',
      content: 'ドットインストールでbootstrapの勉強！',
      created_at: '2020-1-9',
      updated_at: '2020-1-9',
    },
    {
      user_id: '2',
      time: '90',
      genre: 'youtube',
      content: '大食いの動画を撮りました！笑',
      created_at: '2020-1-9',
      updated_at: '2020-1-9',
    },
    {
      user_id: '2',
      time: '60',
      genre: 'プログラミング',
      content: 'progate',
      created_at: '2020-1-13',
      updated_at: '2020-1-13',
    },
    {
      user_id: '2',
      time: '90',
      genre: 'youtube',
      content: 'お金の知識を学べます！！',
      created_at: '2020-1-11',
      updated_at: '2020-1-11',
    },
    {
      user_id: '2',
      time: '30',
      genre: '筋トレ・瞑想',
      content: '胸筋を鍛えた！',
      created_at: '2020-1-9',
      updated_at: '2020-1-9',
    },
    {
      user_id: '2',
      time: '60',
      genre: 'プログラミング',
      content: 'サイト模写！',
      created_at: '2020-1-12',
      updated_at: '2020-1-12',
    },
    {
      user_id: '2',
      time: '90',
      genre: 'ブログ',
      content: '1記事生産',
      created_at: '2020-1-12',
      updated_at: '2020-1-12',
    },
    {
      user_id: '2',
      time: '30',
      genre: '資格・読書',
      content: '「池上彰のお金の学校」を読みました！',
      created_at: '2020-1-12',
      updated_at: '2020-1-12',
    },
    {
      user_id: '2',
      time: '60',
      genre: 'プログラミング',
      content: 'progate',
      created_at: '2020-1-11',
      updated_at: '2020-1-11',
    },
    {
      user_id: '2',
      time: '90',
      genre: 'ブログ',
      content: '健康に関する記事です！',
      created_at: '2020-1-11',
      updated_at: '2020-1-11',
    },
    {
      user_id: '2',
      time: '60',
      genre: 'プログラミング',
      content: 'ドットインストール',
      created_at: '2020-1-10',
      updated_at: '2020-1-10',
    },
    {
      user_id: '2',
      time: '90',
      genre: 'ブログ',
      content: '1記事生産',
      created_at: '2020-1-10',
      updated_at: '2020-1-10',
    },
    {
      user_id: '2',
      time: '30',
      genre: '資格・読書',
      content: 'Life Shift読みました！',
      created_at: '2020-1-14',
      updated_at: '2020-1-14',
    },
    {
      user_id: '2',
      time: '60',
      genre: 'プログラミング',
      content: 'ドットインストール',
      created_at: '2020-1-9',
      updated_at: '2020-1-9',
    },
    {
      user_id: '2',
      time: '90',
      genre: 'youtube',
      content: '初投稿！',
      created_at: '2020-1-9',
      updated_at: '2020-1-9',
    },
    {
      user_id: '2',
      time: '30',
      genre: '筋トレ・瞑想',
      content: '背筋を鍛えた！',
      created_at: '2020-1-9',
      updated_at: '2020-1-9',
    },
    {
      user_id: '2',
      time: '60',
      genre: 'プログラミング',
      content: 'ポートフォリオサイト！',
      created_at: '2020-1-8',
      updated_at: '2020-1-8',
    },
    {
      user_id: '2',
      time: '90',
      genre: 'ブログ',
      content: '1記事生産',
      created_at: '2020-1-8',
      updated_at: '2020-1-8',
    },
    {
      user_id: '2',
      time: '30',
      genre: '資格・読書',
      content: '小説',
      created_at: '2020-1-8',
      updated_at: '2020-1-8',
    },
    {
      user_id: '2',
      time: '60',
      genre: 'プログラミング',
      content: 'progate',
      created_at: '2020-1-7',
      updated_at: '2020-1-7',
    },
    {
      user_id: '2',
      time: '90',
      genre: 'ブログ',
      content: '1記事生産',
      created_at: '2020-1-7',
      updated_at: '2020-1-7',
    },
    {
      user_id: '2',
      time: '30',
      genre: '資格・読書',
      content: 'ビジネス書',
      created_at: '2020-1-7',
      updated_at: '2020-1-7',
    },
    {
      user_id: '2',
      time: '60',
      genre: 'プログラミング',
      content: 'progate',
      created_at: '2020-1-6',
      updated_at: '2020-1-6',
    },
    {
      user_id: '2',
      time: '90',
      genre: 'ブログ',
      content: '筋トレに関する記事投稿！',
      created_at: '2020-1-6',
      updated_at: '2020-1-6',
    },
    {
      user_id: '2',
      time: '30',
      genre: '資格・読書',
      content: '流行りの小説を読みました！',
      created_at: '2020-1-6',
      updated_at: '2020-1-6',
    },
    {
      user_id: '2',
      time: '45',
      genre: 'プログラミング',
      content: 'ドットインストール',
      created_at: '2020-1-5',
      updated_at: '2020-1-5',
    },
    {
      user_id: '2',
      time: '90',
      genre: '物販・せどり',
      content: 'ポイントせどり開始！',
      created_at: '2020-1-5',
      updated_at: '2020-1-5',
    },
    {
      user_id: '2',
      time: '30',
      genre: '資格・読書',
      content: 'ビジネス書',
      created_at: '2020-1-5',
      updated_at: '2020-1-5',
    },

    {
      user_id: '2',
      time: '60',
      genre: 'プログラミング',
      content: 'ドットインストール',
      created_at: '2020-1-4',
      updated_at: '2020-1-4',
    },
    {
      user_id: '2',
      time: '90',
      genre: 'ブログ',
      content: '主婦の節約術に関する記事！',
      created_at: '2020-1-4',
      updated_at: '2020-1-4',
    },
    {
      user_id: '2',
      time: '30',
      genre: '筋トレ・瞑想',
      content: 'ジムで筋トレ！',
      created_at: '2020-1-4',
      updated_at: '2020-1-4',
    },

    {
      user_id: '2',
      time: '90',
      genre: 'ブログ',
      content: '1記事生産',
      created_at: '2020-1-3',
      updated_at: '2020-1-3',
    },
    {
      user_id: '2',
      time: '30',
      genre: '筋トレ・瞑想',
      content: 'ジムで筋トレ',
      created_at: '2020-1-3',
      updated_at: '2020-1-3',
    },

    {
      user_id: '2',
      time: '60',
      genre: 'プログラミング',
      content: 'ドットインストール',
      created_at: '2020-1-2',
      updated_at: '2020-1-2',
    },
    {
      user_id: '2',
      time: '60',
      genre: '動画編集',
      content: 'youtubeの動画編集',
      created_at: '2020-1-2',
      updated_at: '2020-1-2',
    },






    {
      user_id: '3',
      time: '45',
      genre: 'プログラミング',
      content: 'サイト模写！',
      created_at: '2020-1-15',
      updated_at: '2020-1-15',
    },
    {
      user_id: '3',
      time: '90',
      genre: '物販・せどり',
      content: 'ポイントせどり開始！',
      created_at: '2020-1-15',
      updated_at: '2020-1-15',
    },
    {
      user_id: '3',
      time: '90',
      genre: 'ブログ',
      content: '1記事生産',
      created_at: '2020-1-14',
      updated_at: '2020-1-14',
    },
    {
      user_id: '3',
      time: '30',
      genre: '資格・読書',
      content: '2100年の科学ライフを読みました！',
      created_at: '2020-1-14',
      updated_at: '2020-1-14',
    },
    {
      user_id: '3',
      time: '60',
      genre: 'プログラミング',
      content: 'オリジナルサイト制作！',
      created_at: '2020-1-12',
      updated_at: '2020-1-12',
    },
    {
      user_id: '3',
      time: '90',
      genre: 'ブログ',
      content: '筋トレに関する記事投稿！',
      created_at: '2020-1-12',
      updated_at: '2020-1-12',
    },
    {
      user_id: '3',
      time: '30',
      genre: '資格・読書',
      content: '流行りのビジネス書を読みました！',
      created_at: '2020-1-12',
      updated_at: '2020-1-12',
    },
    {
      user_id: '3',
      time: '45',
      genre: 'プログラミング',
      content: 'サイト模写！',
      created_at: '2020-1-12',
      updated_at: '2020-1-12',
    },
    {
      user_id: '3',
      time: '90',
      genre: '物販・せどり',
      content: 'ポイントせどり開始！',
      created_at: '2020-1-12',
      updated_at: '2020-1-12',
    },
    {
      user_id: '3',
      time: '30',
      genre: '資格・読書',
      content: 'ビジネス書',
      created_at: '2020-1-5',
      updated_at: '2020-1-5',
    },

    {
      user_id: '3',
      time: '60',
      genre: 'プログラミング',
      content: 'ドットインストール',
      created_at: '2020-1-10',
      updated_at: '2020-1-10',
    },
    {
      user_id: '3',
      time: '90',
      genre: 'ブログ',
      content: '日常系',
      created_at: '2020-1-10',
      updated_at: '2020-1-10',
    },
    {
      user_id: '3',
      time: '30',
      genre: '筋トレ・瞑想',
      content: 'ジムで筋トレ！',
      created_at: '2020-1-4',
      updated_at: '2020-1-4',
    },

    {
      user_id: '3',
      time: '90',
      genre: 'ブログ',
      content: '1記事生産',
      created_at: '2020-1-3',
      updated_at: '2020-1-3',
    },
    {
      user_id: '3',
      time: '30',
      genre: '筋トレ・瞑想',
      content: 'ジムで筋トレ',
      created_at: '2020-1-3',
      updated_at: '2020-1-3',
    },

    {
      user_id: '3',
      time: '60',
      genre: 'プログラミング',
      content: 'ドットインストール',
      created_at: '2020-1-10',
      updated_at: '2020-1-10',
    },
    {
      user_id: '3',
      time: '60',
      genre: '動画編集',
      content: 'youtubeの動画編集',
      created_at: '2020-1-10',
      updated_at: '2020-1-10',
    }
  ]
)